package BlockChain.patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2017_2.*
import jetbrains.buildServer.configs.kotlin.v2017_2.buildSteps.VisualStudioStep
import jetbrains.buildServer.configs.kotlin.v2017_2.buildSteps.dotnetBuild
import jetbrains.buildServer.configs.kotlin.v2017_2.buildSteps.dotnetRestore
import jetbrains.buildServer.configs.kotlin.v2017_2.buildSteps.visualStudio
import jetbrains.buildServer.configs.kotlin.v2017_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with uuid = 'e8ea34ee-f569-489d-a784-ad8e4d188841' (id = 'BlockChain_Build')
accordingly and delete the patch script.
*/
changeBuildType("e8ea34ee-f569-489d-a784-ad8e4d188841") {
    expectSteps {
        dotnetRestore {
            projects = "Building_Blockchain.sln"
        }
        dotnetBuild {
            projects = "Building_Blockchain.sln"
        }
        visualStudio {
            enabled = false
            path = "Building_Blockchain.sln"
            version = VisualStudioStep.VisualStudioVersion.vs2013
            msBuildVersion = VisualStudioStep.MSBuildVersion.V12_0
            msBuildToolsVersion = VisualStudioStep.MSBuildToolsVersion.V12_0
        }
    }
    steps {
        update<VisualStudioStep>(2) {
            enabled = true
        }
    }
}
